server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/db/changelog-master.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

